server:
  port: 8002

spring:
  application:
    name: loan-service
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/lending_app_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}
  connection-timeout: 5000
  listener:
    simple:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2
        max-interval: 10000
  exchange:
    loan: loan-exchange
    notification: notification.exchange
  queue:
    loan-processing: loan-processing-queue
    loan-approval: loan-approval-queue
    loan-disbursement: loan-disbursement-queue
    loan-repayment: loan-repayment-queue
    loan-status: notification.loan.status
  routing-key:
    process-loan: process.loan
    approve-loan: approve.loan
    disburse-loan: disburse.loan
    repay-loan: loan.repayment
    loan-status: loan.status

app:
  scheduler:
    overdue-loan-check:
      cron: 0 0 1 * * ?  # Run at 1 AM every day
    due-date-reminder:
      cron: 0 0 9 * * ?  # Run at 9 AM every day
  loan-service:
    base-url: http://${LOAN_SERVICE_HOST:loan-service}:${LOAN_SERVICE_PORT:8803}
  notification-service:
    base-url: http://${NOTIFICATION_SERVICE_HOST:notification-service}:${NOTIFICATION_SERVICE_PORT:8804}

loan:
  application:
    expiry-days: 7

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

