server:
  port: 8001

spring:
  application:
    name: customer-service
  r2dbc:
#    url: r2dbc:postgresql://postgres-db}:${DB_PORT:5432}/lending_app_db
    url: r2dbc:postgresql://postgres-db:5432/lending_app_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}
  connection-timeout: 5000
  listener:
    simple:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2
        max-interval: 10000
  exchange:
    notification: notification.exchange
  queue:
    customer-created: notification.customer.created.queue
  routing-key:
    customer-created: customer.created

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

loan:
  scoring:
    rules:
      - minAge: 18
        maxAge: 25
        limit: 1000
      - minAge: 26
        maxAge: 35
        limit: 5000
      - minAge: 36
        maxAge: 50
        limit: 20000
      - minAge: 51
        maxAge: 200
        limit: 75000
