server:
  port: 8003

spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://postgres:5442/lending_app_db
    username: postgres
    password: pass@word1
    driver-class-name: org.postgresql.Driver
    properties:
      schema: public

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka


