server:
  port: 8003

spring:
  application:
    name: product-service
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/lending_app_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
#      defaultZone: http://localhost:8761/eureka


